### ISSUE TITLE
I just dont know what im doing zzzz

### ISSUE THREAD

**Issue by Lon3wolfz** [JannikBirn/palworld-host-save-fix#14]
Only the new level 0 character is shown and not the old one, I don't see the house, etc. but my friend was able to see their explored map. This happened to be yesterday after the 1.4 update so idk if it has to do with that but when i tried to use it under a backup file from yesterday, the fix-it application just crash. I just don't understand what I'm doing please help.

**Comment by JannikBirn** [comment]
It might be related to the 1.4 update, but I don't know for sure. Can you upload your save folder somewhere and send me a link, so I can take a look at it?

**Comment by Lon3wolfz** [comment]
[244E2CDB4277857201679B895137B4CE.zip](https://github.com/JannikBirn/palworld-host-save-fix/files/14157870/244E2CDB4277857201679B895137B4CE.zip)

**Comment by Lon3wolfz** [comment]
Does the application only works when u change server? cus rn I'm using window server.

**Comment by Lon3wolfz** [comment]
[Level.sav.json](https://github.com/JannikBirn/palworld-host-save-fix/files/14158385/Level.sav.json)

**Comment by Lon3wolfz** [comment]
is it this?

**Comment by JannikBirn** [comment]
Nope, this one also doesn't contain a player. You can search inside the JSON converted Level.sav for `IsPlayer` and can find out how many players exist inside that file.

**Comment by Lon3wolfz** [comment]
There should be 9 players, idk why it's not working
![image](https://github.com/JannikBirn/palworld-host-save-fix/assets/158799157/1541a19d-243e-4733-9b5f-7d150a58dc4d)
On here you can see the player and everything but when i try searching the file on github it is not there

**Comment by Lon3wolfz** [comment]
![image](https://github.com/JannikBirn/palworld-host-save-fix/assets/158799157/b7f6eb0b-065c-4509-8c78-5f6cbac9621f)
Ya like its not there when searching the file on github

**Comment by Lon3wolfz** [comment]
[244E2CDB4277857201679B895137B4CE.zip](https://github.com/JannikBirn/palworld-host-save-fix/files/14158463/244E2CDB4277857201679B895137B4CE.zip)

**Comment by Lon3wolfz** [comment]
Can you check if this work? If not then i really dont know. zzzz

**Comment by JannikBirn** [comment]
Nope, this doesn't look correct either. The Player folder seems to be correct, but your Level.sav looks like a new save without any Players registered in it. Maybe the server overwritten it before you made the backup?

**Comment by Lon3wolfz** [comment]
oof, thank you tho
