### ISSUE TITLE
Cant pickup Pals

### ISSUE THREAD

**Issue by Apex664** [JannikBirn/palworld-host-save-fix#2]
So i was doing the transfer from CO-OP to a hosted Server i did the transfer with all the ids from my friends. everything worked i suppose cause me and all my friends got the inventory and pals from the old coop save. but the thing is none of us can pick up pals anymore or have the info box on the downside of the screen when looking at a pal. 

is there a way to fix this?

**Comment by JannikBirn** [comment]
So I assume you used my script and it is still not working. It is hard to say why it's not working I already heard of multiple different solutions for this problem, but without seeing your save files I can't say for sure what your exact problem is. Could you provide me a link to your save file?

**Comment by Apex664** [comment]
u need the Level.sav or Level.sav and Players ****.sav?

**Comment by JannikBirn** [comment]
The `Level.sav` probably is enough.

**Comment by Apex664** [comment]
https://file.io/9YZinEKeInqg

**Comment by JannikBirn** [comment]
It appears that some pals still dont have the correct player guid.
```
...
"OwnerPlayerUId": {
"struct_type": "Guid",
"struct_id": "00000000-0000-0000-0000-000000000000",
"id": null,
"value": "00000000-0000-0000-0000-000000000001",
"type": "StructProperty"
},
"OldOwnerPlayerUIds": {
"array_type": "StructProperty",
"id": null,
"value": {
	"prop_name": "OldOwnerPlayerUIds",
	"prop_type": "StructProperty",
	"values": [
		"00000000-0000-0000-0000-000000000001"
	],
	"type_name": "Guid",
	"id": "00000000-0000-0000-0000-000000000000"
},
"type": "ArrayProperty"
},
...
```
Highlighting the fields `"value": "00000000-0000-0000-0000-000000000001",` this guid should have been replaced with your new guid by my script. 
Just to be sure, you used my script and not the one from [xNul](https://github.com/xNul/palworld-host-save-fix)?
Btw. your guild setup looks right, what is unexpected for me.
It might be possible to adjust the script in a way that it will fix these issues in a second run. But i'll not be able to fix that until tomorrow. For now maybe your problem will be fixed if you try to run the script with the newest commit.

**Comment by Apex664** [comment]
I just tested it again and I realized that I actually used the version of xNul I am still new to the scripting scene I really thought it would be the same until I realized that the two methods are not the same. Now I have done everything again as in your instructions and everything worked perfectly thanks again for the help.

**Comment by JannikBirn** [comment]
Great to hear that it worked!
