### ISSUE TITLE
Using the GUI, the new .sav file is with lower characters

### ISSUE THREAD

**Issue by RobbinMarcus** [JannikBirn/palworld-host-save-fix#7]
Thanks for making this GUI, it worked out great transferring a windows co-op to a linux server so far!

The only issue I encountered is when converting the host character to a new character using the GUI:
The new .sav file was using lower characters: `abc123000000.sav` where it should be `ABC1230000000.sav`.
The save doesn't recognize the host joining because of this, and you have to make a new character (which then creates the save file with capitalized letters).

**Comment by JannikBirn** [comment]
You're right, fixed with this release https://github.com/JannikBirn/palworld-host-save-fix/releases/tag/v.0.1.1
